const API_URL="https://crystal-idle-api.onrender.com";
let token=localStorage.getItem("crystal_idle_token")||"";let character=null;let selectedEnemy=null;
const $=(id)=>document.getElementById(id);
async function api(path,options={}){const headers={"Content-Type":"application/json",...(options.headers||{})};if(token)headers.Authorization=`Bearer ${token}`;const res=await fetch(`${API_URL}${path}`,{...options,headers});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.message||`HTTP ${res.status}`);return data}
function status(id,msg){$(id).textContent=msg}
function renderCharacter(c){character=c;$("name").textContent=c?.name||"---";$("className").textContent=c?.class||"---";$("level").textContent=c?.level??0;$("xp").textContent=c?.xp??0;$("gold").textContent=c?.gold??0;$("power").textContent=c?.power??0;$("atk").textContent=c?.atk??0;$("def").textContent=c?.def??0;$("hp").textContent=`${c?.currentHp??0}/${c?.maxHp??0}`;$("crit").textContent=`${Math.round((c?.critChance??0)*1000)/10}%`;$("zone").textContent=c?.currentZone?.name||"---";if(c?.currentZone?.enemies)renderEnemies(c.currentZone.enemies)}
function renderEnemies(enemies){$("enemySelect").innerHTML="";enemies.forEach(e=>{const o=document.createElement("option");o.value=e.id;o.textContent=`${e.name}${e.isBoss?" (Boss)":""}`;$("enemySelect").appendChild(o)});selectedEnemy=enemies[0]||null;renderEnemy()}
function renderEnemy(){if(!selectedEnemy){$("enemyName").textContent="---";$("enemyStats").textContent="---";return}$("enemyName").textContent=selectedEnemy.name;$("enemyStats").textContent=`HP ${selectedEnemy.maxHp} | ATK ${selectedEnemy.atk} | DEF ${selectedEnemy.def} | XP ${selectedEnemy.xpReward} | Gold ${selectedEnemy.goldReward}`}
async function register(){try{status("authStatus","Registrando...");const data=await api("/auth/register",{method:"POST",body:JSON.stringify({email:$("email").value.trim(),password:$("password").value,characterName:$("characterName").value.trim()})});token=data.token;localStorage.setItem("crystal_idle_token",token);status("authStatus","Registro correcto.");renderCharacter(data.character);loadLeaderboard()}catch(e){status("authStatus",`Error: ${e.message}`)}}
async function login(){try{status("authStatus","Iniciando sesión...");const data=await api("/auth/login",{method:"POST",body:JSON.stringify({email:$("email").value.trim(),password:$("password").value})});token=data.token;localStorage.setItem("crystal_idle_token",token);status("authStatus","Sesión iniciada.");renderCharacter(data.character);loadLeaderboard()}catch(e){status("authStatus",`Error: ${e.message}`)}}
async function loadCharacter(){if(!token)return status("authStatus","Primero inicia sesión.");try{const data=await api("/character/me");renderCharacter(data.data)}catch(e){status("authStatus",`Error: ${e.message}`)}}
async function killEnemy(){if(!selectedEnemy)return status("combatStatus","No hay enemigo seleccionado.");try{status("combatStatus",`Matando ${selectedEnemy.name}...`);const data=await api("/combat/kill",{method:"POST",body:JSON.stringify({enemyTypeId:selectedEnemy.id})});const r=data.data;status("combatStatus",`${data.message}. +${r.goldEarned} gold, +${r.xpEarned} XP.`);renderCharacter(r.character);loadLeaderboard()}catch(e){status("combatStatus",`Error: ${e.message}`)}}
async function claimOffline(){try{status("combatStatus","Reclamando offline...");const data=await api("/idle/claim-offline",{method:"POST"});const r=data.data;status("combatStatus",`${data.message}. ${r.secondsOffline}s, kills ${r.kills}, +${r.goldEarned} gold, +${r.xpEarned} XP.`);renderCharacter(r.character);loadLeaderboard()}catch(e){status("combatStatus",`Error: ${e.message}`)}}
async function upgrade(stat){try{status("upgradeStatus",`Mejorando ${stat}...`);const data=await api("/character/upgrade-stat",{method:"POST",body:JSON.stringify({stat})});status("upgradeStatus",data.message);renderCharacter(data.data.character);loadLeaderboard()}catch(e){status("upgradeStatus",`Error: ${e.message}`)}}
async function loadLeaderboard(){try{const data=await api("/leaderboard/power");$("leaderboard").innerHTML="";data.data.forEach(row=>{const tr=document.createElement("tr");tr.innerHTML=`<td>${row.rank}</td><td>${row.name}</td><td>${row.class}</td><td>${row.level}</td><td>${row.power}</td><td>${row.currentZone?.name||"---"}</td>`;$("leaderboard").appendChild(tr)})}catch(e){$("leaderboard").innerHTML=`<tr><td colspan="6">Error: ${e.message}</td></tr>`}}
$("registerBtn").onclick=register;$("loginBtn").onclick=login;$("refreshCharacterBtn").onclick=loadCharacter;$("killBtn").onclick=killEnemy;$("offlineBtn").onclick=claimOffline;$("leaderboardBtn").onclick=loadLeaderboard;
document.querySelectorAll(".upgradeGrid button").forEach(b=>b.onclick=()=>upgrade(b.dataset.stat));
$("enemySelect").onchange=()=>{const enemies=character?.currentZone?.enemies||[];selectedEnemy=enemies.find(e=>e.id===$("enemySelect").value)||null;renderEnemy()};
(async()=>{await loadLeaderboard();if(token){status("authStatus","Token guardado encontrado.");await loadCharacter()}})();
